### ISSUE TITLE
get_fast_AJI

### ISSUE THREAD

**Issue by zhangliutong** [vqdang/xy_net#3]
When we use the get_fast_AJI to calculate the original AJI, I find that this function just add the missed GT to the denominator.This is a little difference from the original AJI. Does this have an impact on the results？

**Comment by vqdang** [comment]
Hi, first of all, could you tell me in more detail where do you think is problematic (code location, reference between file and file etc.) ? As of now, I don't have enough context to answer you. 

Anyways, in case you are wondering about 
https://github.com/vqdang/xy_net/blob/bfaa82d80ae40fab08ef0637f499f04203480191/src/metrics/stats_utils.py#L70-L74
and I'm assuming the **missed GT** you mentioned means [GT instance failed to get detected].

Those line matches with https://github.com/vqdang/xy_net/blob/bfaa82d80ae40fab08ef0637f499f04203480191/src/metrics/aggregated_jaccard_index.m#L67
for the situation where there is no prediction overlapping with the GT instance at all. 

**nnz** counts non zero pixels of map (or-ing/union between GT and predicted instance binary map). 

However, because our code only uses `max union value` (default to 0) and `max union value` is only updated when IoU > 0 between GT and prediction. The code will be incorrect in case of having no prediction for GT under consideration, hence, we add the sum of just GT back to match with the matlab line.

**Comment by zhangliutong** [comment]
Thank you so much. I made a mistake.

**Comment by zhangliutong** [comment]
![1551751822 1](https://user-images.githubusercontent.com/38174135/53775860-f8febb80-3f2e-11e9-94dd-8c07b64d956f.jpg)
In the original AJI, the author not only add the missed GT,but also add the first Predicted nuclei.

**Comment by vqdang** [comment]
Hi, you should reread the entire comment portion again. In fact, [adding the first Predicted nuclei together with the failing to be detected GT instance] is the bug we mentioned in their code. 

So, as a thought experiment, let's assume the first predicted nuclei (it will have ID of  1) have its overlapping ground truth instance having ID of Y. Within this iteration for ground truth instance having ID of X (with X < Y, hence X get evaluated before Y), GT instance X has no predicted nuclei. As a result, if we use their matlab code as it is, GT instance X will be added together with predicted instance 1 and then, predicted instance 1 is removed from later calculation. This in turn leads to wrong evaluation on ground truth Y iteration later. On the other hand, if we assume that GT instance X with X=1, then, the matlab code will not be wrong later because there is no more predicted nuclei ID to be evaluated.
https://github.com/vqdang/xy_net/blob/bfaa82d80ae40fab08ef0637f499f04203480191/src/metrics/aggregated_jaccard_index.m#L69-L70

Beside that, the default behavior of 
https://github.com/vqdang/xy_net/blob/bfaa82d80ae40fab08ef0637f499f04203480191/src/metrics/aggregated_jaccard_index.m#L67
is adding the union of matched predicted instance and its corresponding GT to the denominator (as I have analyzed the code above). Therefore, it's incorrect to add First Predicted nuclei to the failing to be detected GT instance (`missed GT`).

This is a little subtle bug due to the default behavior of default return of `argmax`, hence we had fixed that behavior within the `get_fast_aji`.

**Comment by zhangliutong** [comment]
Thank you so much.
